# Create image based on the official Node 10 image from dockerhub
FROM node:12-alpine3.11

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY backend/yarn.lock /usr/src/app

# Install dependecies
RUN yarn install

# Get all the code needed to run the app
COPY backend/ /usr/src/app

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
CMD ["yarn", "start:dev"]